#!/bin/bash

# See documentation for details:
# https://docs.docker.com/docker-hub/builds/advanced/

if [ -n "${DOCKER_PASSWORD}" ] && [ -n "${DOCKER_LOGIN}" ]; then
    if [ -n "${DOCKER_REGISTRY}" ]; then
        echo "Login to Docker Registry ${DOCKER_REGISTRY}..."
        echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_LOGIN}" --password-stdin "${DOCKER_REGISTRY}"
    else
        echo "Login to Docker default Registry..."
        echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_LOGIN}" --password-stdin
    fi
fi

docker buildx ls

docker buildx create \
    --platform "${PLATFORMS}" \
    --name "buildx_push_${SOURCE_COMMIT}" \
    --use

docker buildx inspect "buildx_push_${SOURCE_COMMIT}"
